ui-mobileapp/App.tsx
ui-mobileapp/theme/border.ts
ui-mobileapp/theme/colors.ts
ui-mobileapp/theme/fonts.ts
ui-mobileapp/theme/reset.ts
ui-mobileapp/theme/styled.d.ts
ui-mobileapp/theme/theme.ts

Add `/theme` folder in `ui-mobileapp`

---

ui-mobileapp/App.tsx
ui-mobileapp/package-lock.json
ui-mobileapp/package.json
ui-mobileapp/src/navigation/BottomTabNavigator.tsx
ui-mobileapp/src/navigation/RootStackNavigator.tsx
ui-mobileapp/src/navigation/StackNavigationParams.ts
ui-mobileapp/src/screens/Chat.tsx
ui-mobileapp/src/screens/Home.tsx
ui-mobileapp/src/screens/Posts.tsx
ui-mobileapp/src/screens/Profile.tsx
ui-mobileapp/src/screens/Publish.tsx
ui-mobileapp/src/screens/SignIn.tsx
ui-mobileapp/src/screens/SignUp.tsx

- add BottomTab navigator (navigation menu)
- add RootStack navigator (home/signup/signin screen)
- add navigaion test on homepage
doc: https://reactnavigation.org/docs/stack-navigator/

`mobileapp` - add navigation stack

---

ui-mobileapp/App.tsx
ui-mobileapp/src/components/atoms/Button.tsx
ui-mobileapp/src/components/atoms/Text.tsx
ui-mobileapp/src/theme/border.ts
ui-mobileapp/src/theme/fonts.ts

add `Button` & `Text` atom components

---

ui-mobileapp/package-lock.json
ui-mobileapp/package.json
ui-mobileapp/src/common/forms/validationConstants.ts
ui-mobileapp/src/components/atoms/Input.tsx
ui-mobileapp/src/components/organisms/register/RegisterStepFinal.tsx
ui-mobileapp/src/components/organisms/register/RegisterStepOne.tsx
ui-mobileapp/src/components/organisms/register/RegisterStepTwo.tsx
ui-mobileapp/src/components/organisms/register/registerValidationSchemas.ts
ui-mobileapp/src/navigation/RootStackNavigator.tsx
ui-mobileapp/src/screens/Login.tsx
ui-mobileapp/src/screens/Register.tsx
ui-mobileapp/src/screens/SignUp.tsx

- install yup and react-hook-form
- add multi-steps register form
- add `Input` atom
- validation schemas
https://user-images.githubusercontent.com/56693082/157675011-c5d1df00-28b3-4b9c-a29a-ff43de4f4760.mov

add `register` form

---

ui-mobileapp/src/components/atoms/Button.tsx
ui-mobileapp/src/components/atoms/Spinner.tsx
ui-mobileapp/src/components/atoms/Text.tsx
ui-mobileapp/src/components/organisms/LoginForm/LoginForm.tsx
ui-mobileapp/src/components/organisms/RegisterSteps/RegisterStepFinal.tsx
ui-mobileapp/src/components/organisms/RegisterSteps/RegisterStepOne.tsx
ui-mobileapp/src/components/organisms/RegisterSteps/RegisterStepTwo.tsx

(je m'occupe de rebase sur staging plus tard)
DEMO:
https://user-images.githubusercontent.com/56693082/162855498-17efa620-2143-42f3-8087-e95a9730230a.mov

add loading button state

---

ui-mobileapp/src/navigation/BottomTabNavigator.tsx
ui-mobileapp/src/navigation/StackNavigationParams.ts
ui-mobileapp/src/screens/Missions.tsx

rename Posts page to Misisons

---

ui-mobileapp/src/navigation/BottomTabNavigator.tsx
ui-mobileapp/src/navigation/StackNavigationParams.ts
ui-mobileapp/src/screens/Shop.tsx

27 add shop page

---

.github/CODEOWNERS
.github/pull_request_template.md
ui-mobileapp/src/components/atoms/Button.tsx
ui-mobileapp/src/components/atoms/Spinner.tsx
ui-mobileapp/src/components/atoms/Text.tsx
ui-mobileapp/src/components/organisms/LoginForm/LoginForm.tsx
ui-mobileapp/src/components/organisms/RegisterSteps/RegisterStepFinal.tsx
ui-mobileapp/src/components/organisms/RegisterSteps/RegisterStepOne.tsx
ui-mobileapp/src/components/organisms/RegisterSteps/RegisterStepTwo.tsx
ui-mobileapp/src/navigation/BottomTabNavigator.tsx
ui-mobileapp/src/navigation/StackNavigationParams.ts
ui-mobileapp/src/screens/Missions.tsx
ui-mobileapp/src/screens/Shop.tsx
ui-mobileapp/src/theme/colors.ts

(ne pas merge juste j'ouvre la PR)

Staging -> Main (don't merge now)

---

ui-mobileapp/src/components/atoms/Text.tsx

fix(ui-mobileapp): fix duplicate function to Text atom

---

ui-mobileapp/App.tsx
ui-mobileapp/src/components/atoms/Text.tsx
ui-mobileapp/src/navigation/BottomTabNavigator.tsx
ui-mobileapp/src/theme/fonts.ts
ui-mobileapp/src/theme/utils.ts

Add tab bar style

---

ui-mobileapp/App.tsx
ui-mobileapp/package-lock.json
ui-mobileapp/package.json
ui-mobileapp/src/common/hooks/useCachedResources.ts
ui-mobileapp/src/screens/Loading.tsx

Create loading screen
- add loading screen (wip-
- add `useCachedResources.ts` hook
Fixed #25

25 - create loading screen

---

ui-mobileapp/src/navigation/RootStackNavigator.tsx
ui-mobileapp/src/navigation/StackNavigationParams.ts
ui-mobileapp/src/screens/Loading.tsx
ui-mobileapp/src/screens/Missions.tsx
ui-mobileapp/src/screens/uniques/Mission.tsx

- add fake data and redirection to unique page
- Create single mission page

Add single mission page

---

ui-mobileapp/src/components/atoms/Text.tsx
ui-mobileapp/src/navigation/RootStackNavigator.tsx
ui-mobileapp/src/navigation/StackNavigationParams.ts
ui-mobileapp/src/screens/Explanation.tsx
ui-mobileapp/src/screens/Loading.tsx

feat(ui-mobileapp): create explanation screen instead of homepage

---

ui-mobileapp/src/components/atoms/Box.tsx

add Box atom component

---

ui-mobileapp/src/components/atoms/Input.tsx
ui-mobileapp/src/components/layouts/MainLayout.tsx
ui-mobileapp/src/components/molecules/InputGroup.tsx
ui-mobileapp/src/theme/colors.ts

54 -  add input text style

---

ui-mobileapp/src/components/atoms/Button.tsx

 update padding to our Button with spacing tokens

---

ui-backoffice/package-lock.json
ui-backoffice/package.json
ui-backoffice/src/components/DateFnsProvider/index.tsx
ui-backoffice/src/content/pages/Management/Jobs/Job/JobForm.tsx
ui-backoffice/src/content/pages/Management/Jobs/Job/index.tsx
ui-backoffice/src/content/pages/Management/Jobs/Jobs.tsx
ui-backoffice/src/content/pages/Management/Jobs/JobsTable.tsx
ui-backoffice/src/content/pages/Management/Litigations/Litigations.tsx
ui-backoffice/src/content/pages/Management/Organizations/Organizations.tsx
ui-backoffice/src/content/pages/Management/Organizations/OrganizationsTable.tsx
ui-backoffice/src/content/pages/Management/Users/Users.tsx
ui-backoffice/src/models/admin.ts
ui-backoffice/src/models/job.ts
ui-backoffice/src/models/user.ts
ui-backoffice/src/router.tsx

Job details page with edit form

BO - job page

---

ui-backoffice/src/content/pages/Management/Litigations/Litigation/LitigationForm.tsx
ui-backoffice/src/content/pages/Management/Litigations/Litigation/index.tsx
ui-backoffice/src/content/pages/Management/Litigations/Litigations.tsx
ui-backoffice/src/content/pages/Management/Litigations/LitigationsTable.tsx
ui-backoffice/src/models/litigation.ts
ui-backoffice/src/router.tsx

Litigations details page + form

Bo litigations page

---

ui-backoffice/src/content/pages/Management/Users/User/UserForm.tsx
ui-backoffice/src/content/pages/Management/Users/User/index.tsx
ui-backoffice/src/content/pages/Management/Users/UsersTable.tsx
ui-backoffice/src/router.tsx

feat-BO-user-page: user page + form templates + add link into UsersTable

---

ui-mobileapp/src/assets/icons/Info.tsx
ui-mobileapp/src/components/atoms/Alert.tsx
ui-mobileapp/src/components/atoms/Icon/Icon.tsx
ui-mobileapp/src/components/atoms/Text.tsx
ui-mobileapp/src/components/organisms/RegisterSteps/RegisterStepFinal.tsx
ui-mobileapp/src/components/organisms/RegisterSteps/RegisterStepTwo.tsx
ui-mobileapp/src/screens/Register.tsx
ui-mobileapp/src/theme/utils.ts

- add `Alert` atom 
- add alert on register two step

Add alert on register screens

---

ui-mobileapp/src/assets/icons/Info.tsx
ui-mobileapp/src/components/atoms/Alert.tsx
ui-mobileapp/src/components/atoms/Icon/Icon.tsx
ui-mobileapp/src/components/atoms/ProgressBar.tsx
ui-mobileapp/src/components/atoms/Text.tsx
ui-mobileapp/src/components/organisms/RegisterSteps/RegisterStepFinal.tsx
ui-mobileapp/src/components/organisms/RegisterSteps/RegisterStepTwo.tsx
ui-mobileapp/src/navigation/RootStackNavigator.tsx
ui-mobileapp/src/screens/Register.tsx
ui-mobileapp/src/theme/utils.ts

- add `ProgressBar` atom
- add logic of register progress bar

Add progress bar register

---

ui-mobileapp/src/assets/icons/Arrow.tsx
ui-mobileapp/src/assets/icons/Info.tsx
ui-mobileapp/src/components/atoms/Icon/Icon.tsx
ui-mobileapp/src/components/layouts/MainLayout.tsx
ui-mobileapp/src/components/molecules/GoBackButton.tsx
ui-mobileapp/src/screens/Register.tsx

Add back button

---

ui-backoffice/src/models/discount.ts

feat(BO-models): add duration prop to Discount

---

ui-backoffice/src/models/discount.ts

discout model update

---

ui-backoffice/src/models/user.ts

feat(BO-models): add organizations prop to User

---

ui-backoffice/src/models/discount.ts
ui-backoffice/src/models/user.ts

update user model

---

ui-mobileapp/src/assets/icons/Calendar.tsx
ui-mobileapp/src/assets/icons/Heart.tsx
ui-mobileapp/src/assets/icons/Location.tsx
ui-mobileapp/src/components/atoms/Box.tsx
ui-mobileapp/src/components/atoms/Button.tsx
ui-mobileapp/src/components/layouts/MainLayout.tsx
ui-mobileapp/src/components/molecules/MissionDetail.tsx
ui-mobileapp/src/components/molecules/ShopCard.tsx
ui-mobileapp/src/screens/Explanation.tsx
ui-mobileapp/src/screens/Missions.tsx
ui-mobileapp/src/screens/uniques/Mission.tsx
ui-mobileapp/src/theme/fonts.ts

add design single mission page

---

ui-mobileapp/App.tsx
ui-mobileapp/package-lock.json
ui-mobileapp/package.json
ui-mobileapp/src/assets/icons/Error.tsx
ui-mobileapp/src/assets/icons/Success.tsx
ui-mobileapp/src/components/atoms/Button.tsx
ui-mobileapp/src/components/atoms/Toast.tsx
ui-mobileapp/src/components/molecules/ShopCard.tsx
ui-mobileapp/src/screens/Shop.tsx

Create toast component

---

ui-mobileapp/src/navigation/BottomTabNavigator.tsx
ui-mobileapp/src/navigation/RootStackNavigator.tsx
ui-mobileapp/src/navigation/StackNavigationParams.ts
ui-mobileapp/src/screens/MyAccount.tsx
ui-mobileapp/src/screens/uniques/Mission.tsx
ui-mobileapp/src/screens/uniques/Profile.tsx

- rename the old `Profile` page to `MyAccount`
- add `Profile` generic page
- add Link to Organization profile page on mission page

Add profile/organization single page

---

ui-mobileapp/src/components/atoms/Avatar.tsx
ui-mobileapp/src/screens/uniques/Profile.tsx

Create avatar atom

---

ui-mobileapp/src/components/layouts/MainLayout.tsx
ui-mobileapp/src/components/organisms/LoginForm/LoginForm.tsx
ui-mobileapp/src/navigation/RootStackNavigator.tsx
ui-mobileapp/src/screens/Login.tsx
ui-mobileapp/src/screens/Register.tsx
ui-mobileapp/src/screens/uniques/Mission.tsx

Add login style page

---

ui-mobileapp/package-lock.json
ui-mobileapp/package.json

expo fix dependencies

---

README.md

swagger link

---

api/index.js

Fix typo auth path

---

api/swagger.json

add route swagger auth

---

api/fixtures/13-associations-users.js
api/fixtures/19-participants.js
api/fixtures/20-litigations.js
api/migrations/20220208104202-create-associations-users.js
api/migrations/20220208104640-create-groups.js
api/models/associations_users.js
api/models/favorites.js
api/models/groups.js
api/models/litigations.js
api/models/status.js
api/src/services/Admins/controller.js
api/src/services/Admins/index.js
api/src/services/Authentications/controller.js
api/src/services/Commons/controller.js
api/src/services/Users/controller.js
api/src/services/Users/index.js
api/swagger.json

add routes users to swagger + migrate new data

---

mobileapp/src/common/contexts/AuthContext.tsx
mobileapp/src/components/organisms/LoginForm/LoginForm.tsx
mobileapp/src/navigation/RootStackNavigator.tsx
mobileapp/src/navigation/StackNavigationParams.ts
mobileapp/src/screens/MyAccount.tsx

refactor(mobileapp): fix redirection when the user is connected

---

mobileapp/src/common/api/requests/auth/fetchConnectedUser.ts
mobileapp/src/common/contexts/AuthContext.tsx
mobileapp/src/common/utils/getNameInitials.ts
mobileapp/src/common/utils/tests/createUsername.spec.ts
mobileapp/src/common/utils/tests/getNameInitials.test.ts
mobileapp/src/components/atoms/Avatar.tsx
mobileapp/src/screens/MyAccount.tsx

add Avatar in `MyAccount` screen

---

backoffice/src/components/Form/index.tsx
backoffice/src/models/pricing.ts
backoffice/src/pages/AppsConfiguration/Settings/Difficulties/DifficultyModalContent.tsx
backoffice/src/pages/AppsConfiguration/Settings/DiscountTypes/DiscountTypeModalContent.tsx
backoffice/src/pages/AppsConfiguration/Settings/LitigationObjects/LitigationObjectModalContent.tsx
backoffice/src/pages/AppsConfiguration/Settings/Pricings/PricingModalContent.tsx
backoffice/src/pages/AppsConfiguration/Settings/Pricings/PricingsTable.tsx
backoffice/src/pages/AppsConfiguration/Settings/Roles/RoleModalContent.tsx
backoffice/src/pages/AppsConfiguration/Settings/Statuses/StatusModalContent.tsx
backoffice/src/pages/AppsConfiguration/Settings/Tags/TagModalContent.tsx

Bo parameters

---

.gitignore
docker-compose.yml

fix: docker compose

---

mobileapp/package-lock.json
mobileapp/package.json
mobileapp/src/assets/icons/Scanner.tsx
mobileapp/src/components/layouts/GlobalLayout.tsx
mobileapp/src/components/layouts/subComponents/Header.tsx
mobileapp/src/components/organisms/ExplanationCarousel.tsx
mobileapp/src/navigation/RootStackNavigator.tsx
mobileapp/src/navigation/StackNavigationParams.ts
mobileapp/src/screens/Scanner.tsx
mobileapp/src/screens/uniques/Mission.tsx

- install @expo-barcode-scanner package
- add Scanner page
- add possibility to scan QR Code

Add QR Code scanner 

---

mobileapp/src/assets/icons/Close.tsx
mobileapp/src/assets/icons/Token.tsx
mobileapp/src/components/atoms/Modal.tsx
mobileapp/src/components/atoms/Text.tsx
mobileapp/src/components/layouts/subComponents/Header.tsx
mobileapp/src/components/organisms/TokenButton.tsx

- add `align` prop to `Text` atom
- create `Modal` atom component
- add `TokenButton` component with token modal

Add `Modal` atom

---

mobileapp/src/common/mockedData.ts
mobileapp/src/components/molecules/MissionCard.tsx
mobileapp/src/components/organisms/MissionsList.tsx
mobileapp/src/screens/Missions.tsx
mobileapp/src/screens/uniques/Mission.tsx

Add mission card component without style

---

mobileapp/src/components/atoms/Button.tsx
mobileapp/src/components/atoms/Pill.tsx
mobileapp/src/components/atoms/Radio.tsx
mobileapp/src/components/molecules/PillGroup.tsx
mobileapp/src/components/molecules/RadioGroup.tsx

```jsx
<PillGroup
options={["opt1", "opt2", "opt3", "opt5"]}
handlePress={(data) => setFilters(data)}
/>
// console.log(filters);  returns active pill label
```

Create pill component

---

mobileapp/src/assets/icons/Filter.tsx
mobileapp/src/assets/icons/Sort.tsx
mobileapp/src/components/atoms/Modal.tsx
mobileapp/src/components/atoms/Text.tsx
mobileapp/src/navigation/RootStackNavigator.tsx
mobileapp/src/navigation/StackNavigationParams.ts
mobileapp/src/screens/Missions.tsx
mobileapp/src/screens/MissionsFilter.tsx

Add filter page (without logic)

---

api/src/services/Commons/index.js
api/swagger.json

add route change/status

---

mobileapp/package.json
mobileapp/src/assets/icons/Check.tsx
mobileapp/src/common/api/hooks/useUserConnected.ts
mobileapp/src/common/api/hooks/useUserFavorites.ts
mobileapp/src/common/api/interfaces/PaginatedDataType.ts
mobileapp/src/common/api/requests/addUserFavorite.ts
mobileapp/src/common/api/requests/auth/fetchConnectedUser.ts
mobileapp/src/common/api/requests/deleteFavorite.ts
mobileapp/src/common/api/requests/getUserFavorites.ts
mobileapp/src/common/api/routes.ts
mobileapp/src/common/contexts/AuthContext.tsx
mobileapp/src/common/mockedData.ts
mobileapp/src/components/molecules/Carousel.tsx
mobileapp/src/components/molecules/MissionCard.tsx
mobileapp/src/models/favorite.ts
mobileapp/src/navigation/RootStackNavigator.tsx
mobileapp/src/screens/Loading.tsx
mobileapp/src/screens/Missions.tsx
mobileapp/src/screens/MyAccount.tsx
mobileapp/src/screens/uniques/Mission.tsx

mobileapp - add follow feature

---

backoffice/src/pages/User/settings/EditProfileTab.tsx

bo-user-settings:resolve input css

---

api/index.js
api/swagger.json

debug access denied

---

api/index.js
api/swagger.json
backoffice/src/models/partner.ts
backoffice/src/pages/Management/Partners/PartnerModalContent.tsx
backoffice/src/pages/Management/Partners/Partners.tsx
backoffice/src/pages/Management/Partners/PartnersTable.tsx
backoffice/src/router.tsx
backoffice/src/services/config.ts
backoffice/src/services/requestApi.ts
backoffice/src/utils/functions.ts

Bo partners

---

backoffice/src/services/admins.service.ts

fix-bo: fix send log request uri

---

mobileapp/src/common/hooks/useBoolean.ts
mobileapp/src/components/atoms/Input.tsx
mobileapp/src/components/molecules/DateTimePickerInput.tsx
mobileapp/src/components/organisms/TokenButton.tsx
mobileapp/src/screens/Missions.tsx

add `useBoolean` hook

---

webapp/src/hooks/useAuth.tsx
webapp/src/models/index.ts
webapp/src/models/log.ts
webapp/src/models/membership.ts
webapp/src/models/user.ts

Webapp session

---

webapp/src/applications/Organization/Gestion/Jobs/Create/CreatingCard.tsx
webapp/src/applications/Organization/Gestion/Jobs/List/Jobs.tsx
webapp/src/applications/Organization/Gestion/Jobs/List/JobsTable.tsx
webapp/src/applications/Organization/Gestion/Jobs/List/index.tsx
webapp/src/components/Form/index.tsx
webapp/src/components/Modal/DeleteContent.tsx
webapp/src/components/Modal/index.tsx
webapp/src/components/StatusLabel/index.tsx
webapp/src/components/TableWrapper/BulkActions.tsx
webapp/src/components/TableWrapper/index.tsx
webapp/src/hooks/useModal.tsx
webapp/src/services/common.service.ts
webapp/src/services/job.service.ts

feat-webapp: add job table

---

webapp/src/applications/Organization/Gestion/Jobs/Create/CreatingCard.tsx

refacto-webapp: add type to on change difficulty select event

---

api/models/associations.js
api/src/services/Organizations/controller.js
api/swagger/dto.models/organizations.model.js

debug organization association

---

webapp/src/applications/Organization/Gestion/Jobs/List/JobsTable.tsx
webapp/src/applications/Organization/Gestion/Jobs/List/subComponents/JobTableItem.tsx

- add spaces between elements
- extract code to a dedicated file

 webapp - improve readability `JobsTable` component

---

webapp/src/applications/Organization/Gestion/Jobs/List/JobsTable.tsx
webapp/src/applications/Organization/Gestion/Jobs/List/subComponents/DeleteJobModal.tsx
webapp/src/applications/Organization/Gestion/Jobs/List/subComponents/JobTableItem.tsx
webapp/src/components/TableWrapper/index.tsx

webapp -> staging

---

webapp/cypress/e2e/login.cy.ts
webapp/src/pages/SignIn/index.tsx

Add login e2e test flow(wip1)

---

api/src/services/Jobs/controller.js
api/src/services/Jobs/index.js
api/src/services/Participations/controller.js
api/src/services/Participations/index.js
api/swagger/controllers/applications.js
api/swagger/controllers/index.js
api/swagger/controllers/jobs.js
api/swagger/controllers/participations.js
api/swagger/dto.models/index.js
api/swagger/dto.models/participations.model.js
api/swagger/index.js

add route register to job

---

cmd/maj-db.sh

upadte maj db

---

mobileapp/src/components/molecules/Scanner/SuccessModal.tsx
mobileapp/src/components/molecules/Scanner/ValidateJobModal.tsx
mobileapp/src/screens/Scanner.tsx
mobileapp/src/theme/utils.ts

mobileapp - add qr code scanner states (with modal)

---

mobileapp/src/common/api/hooks/useUserJobs.ts
mobileapp/src/common/api/requests/addUserFavorite.ts
mobileapp/src/common/api/requests/job/fetchRegisterJob.ts
mobileapp/src/common/api/routes.ts
mobileapp/src/screens/single/Job.tsx

mobileapp - add data flow to job page

---

api/src/services/Subscriptions/controller.js

fix subscriptions

---

backoffice/src/hooks/useBoolean.ts
webapp/src/hooks/useBoolean.ts

Add use boolean hook to apps

---

mobileapp/package-lock.json
mobileapp/package.json
mobileapp/src/components/organisms/RegisterSteps/RegisterStepFinal.tsx

TODO: Add useAutocompleteGooglePlaces hook (cf https://morioh.com/p/5d15d17f479f?f=5c21fb01c16e2556b555ab32)

add user current location with `expo-location`

---

webapp/src/components/Toast/index.tsx
webapp/src/contexts/ToastContext.tsx
webapp/src/hooks/useApi.ts
webapp/src/hooks/useAuth.tsx
webapp/src/hooks/useToast.tsx
webapp/src/index.tsx
webapp/src/layouts/SidebarLayout/Header/Menu/index.tsx
webapp/src/models/index.ts
webapp/src/models/services.ts
webapp/src/services/auth.service.ts
webapp/src/services/routes.ts

Webapp toaster

---

mobileapp/cypress/e2e/register.cy.ts
mobileapp/src/components/organisms/ExplanationCarousel.tsx
mobileapp/src/components/organisms/RegisterSteps/RegisterStepOne.tsx

Feat/add register integration test (wip)

---

webapp/package.json

Webapp yup

---

api/orm/models/index.js
api/public/views/templates-mail/create-account-user.body.handlebars
api/public/views/templates-mail/partials/footer.handlebars
api/public/views/templates-mail/partials/header.handlebars
api/public/views/templates-mail/partials/template.html
api/src/services/Jobs/controller.js

test debug heroku postgres online

---

mobileapp/src/common/api/interfaces/StatusCode.enum.ts
mobileapp/src/common/contexts/AuthContext.tsx
mobileapp/src/components/organisms/RegisterSteps/RegisterStepFinal.tsx
mobileapp/src/navigation/RootStackNavigator.tsx

add email already exist register

---

api/public/views/templates-mail/partials/head.handlebars
api/public/views/templates-mail/partials/template.html
api/public/views/templates-mail/register-to-job.body.handlebars
api/public/views/templates-mail/update-job.body.handlebars
api/src/services/Admins/controller.js
api/src/services/Discounts/controller.js
api/src/services/Jobs/controller.js
api/src/services/Litigations/controller.js
api/src/services/Organizations/controller.js
api/src/services/Partners/controller.js
api/src/services/Subscriptions/controller.js
api/src/services/Transactions/controller.js
api/src/services/Users/controller.js
api/src/utils/common/mail.json
api/src/utils/common/thenCatch.js

send mail admin

---

mobileapp/app.json
mobileapp/package-lock.json
mobileapp/package.json
mobileapp/src/common/contexts/AuthContext.tsx
mobileapp/src/components/atoms/Slider.tsx
mobileapp/src/screens/JobsFilter.tsx

feat(mobileapp): add `Slider` component to `JobsFilter` page

---

mobileapp/src/components/atoms/Checkbox.tsx
mobileapp/src/screens/JobsFilter.tsx
mobileapp/src/theme/border.ts

Add checkbox component

---

mobileapp/src/components/atoms/Pill.tsx
mobileapp/src/components/molecules/JobCard.tsx

add label tag to JobCard

---

mobileapp/App.tsx
mobileapp/src/common/api/hooks/useDiscount.ts
mobileapp/src/common/api/hooks/useDiscounts.ts
mobileapp/src/common/api/requests/discount/getDiscount.ts
mobileapp/src/common/api/requests/discount/getDiscounts.ts
mobileapp/src/common/api/routes.ts
mobileapp/src/common/contexts/AuthContext.tsx
mobileapp/src/common/hooks/useAuth.ts
mobileapp/src/components/atoms/Avatar.tsx
mobileapp/src/components/molecules/ShopCard.tsx
mobileapp/src/components/organisms/LoginForm/LoginForm.tsx
mobileapp/src/components/organisms/TokenButton.tsx
mobileapp/src/navigation/RootStackNavigator.tsx
mobileapp/src/navigation/StackNavigationParams.ts
mobileapp/src/screens/Jobs.tsx
mobileapp/src/screens/MyAccount.tsx
mobileapp/src/screens/Shop.tsx
mobileapp/src/screens/single/Discount.tsx
mobileapp/src/screens/single/Job.tsx

Add discounts mobileapp

---

api/src/services/Authentications/controller.js
api/src/utils/common/messages.json

add status 403 error messsage for activate account user

---

api/public/views/templates-mail/create-account-user.body.handlebars
api/public/views/templates-mail/reset-password.body.handlebars
api/public/views/templates-mail/verify-account-user.body.handlebars
api/src/routes/index.js
api/src/services/Authentications/controller.js
api/src/services/Authentications/index.js
api/src/utils/enum.json

fix/ debug routes api online

---

api/src/services/Users/controller.js
api/src/services/Users/index.js
api/src/swagger/controllers/admins.js
api/src/swagger/controllers/discounts.js
api/src/swagger/controllers/jobs.js
api/src/swagger/controllers/litigations.js
api/src/swagger/controllers/organizations.js
api/src/swagger/controllers/partners.js
api/src/swagger/controllers/subscriptions.js
api/src/swagger/controllers/transactions.js
api/src/swagger/controllers/users.js
api/src/swagger/dto.models/users.model.js

add route jobs user in a association and add query order

---

api/src/services/Users/index.js
api/src/swagger/controllers/users.js

fix/ debug query memberId to users route

---

api/src/swagger/controllers/users.js

fix/ debug memberId to users toutes

---

api/public/views/templates-mail/reset-password.body.handlebars

fix/ cors request login

---

api/public/views/templates-mail/create-account-user.body.handlebars
api/public/views/templates-mail/register-to-job.body.handlebars
api/public/views/templates-mail/reset-password.body.handlebars
api/public/views/templates-mail/update-job.body.handlebars
api/public/views/templates-mail/verify-account-user.body.handlebars
api/src/services/externals/mailer/index.js

add link template mail

---

api/src/services/Authentications/controller.js
api/src/services/Users/index.js
api/src/swagger/controllers/users.js
api/src/swagger/dto.models/users.model.js

add route activate account user to swagger

---

webapp/src/components/ForgotPasswordForm/index.tsx
webapp/src/components/ResetPasswordForm/index.tsx
webapp/src/models/services.ts
webapp/src/pages/AccountConfirmation/index.tsx
webapp/src/pages/ResetPassword/AfterValidationContent.tsx
webapp/src/pages/ResetPassword/BeforeValidationContent.tsx
webapp/src/pages/ResetPassword/index.tsx
webapp/src/services/auth.service.ts
webapp/src/services/users.service.ts

Webapp email validation / password reset and forgot

---

api/orm/migrations/20220404125103-create-partners.js
api/orm/models/partners.js
api/src/services/Organizations/controller.js
api/src/services/Organizations/interface.js
api/src/services/Partners/controller.js
api/src/services/Partners/interface.js
api/src/swagger/dto.models/organizations.model.js
api/src/swagger/dto.models/partners.model.js
api/src/swagger/generique/index.js

mettre siret sur les routes de création associations+partenaires

---

api/src/fixtures/fakes/14-partners.js
api/src/fixtures/fakes/18-tags-jobs.js
api/src/services/Jobs/controller.js
api/src/services/Jobs/index.js
api/src/swagger/controllers/jobs.js
api/src/swagger/generique/pagination.js
api/src/utils/common/thenCatch.js

debug create job

---

api/src/services/Organizations/controller.js
api/src/services/Partners/controller.js
api/src/services/externals/insee/index.js
docker-compose.yml

implémentation de l'api INSEE

---

api/src/services/Jobs/controller.js

id tags_jobs

---

api/src/utils/common/thenCatch.js

fix/create jobs_2

---

api/src/utils/common/thenCatch.js

fix/create jobs_3

---

api/src/utils/common/thenCatch.js

fix/create jobs_5

---

api/src/utils/common/thenCatch.js

fix/create jobs_6

---

api/src/services/Organizations/controller.js
api/src/utils/common/thenCatch.js

fix/ create job postgres

---

api/src/services/Jobs/controller.js
api/src/utils/common/thenCatch.js

fix/create Job images
